# Site settings
title: Hackference 2015
email: jp@jakelprice.com
description: >
  Hackference 2015 website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackference.github.io/hackference-2015/" # the base hostname & protocol for your site
twitter_username: jakelprice
github_username:  jakeprice86

# Build settings
markdown: kramdown
