# Site settings
title: Hackference 2015
email: jp@jakelprice.com
description: >
  Hackference is a conference and hackathon based around learning and inspiring people to hack - October 2nd, 3rd and 4th 2015 in Birmingham, UK
baseurl: "" # the subpath of your site, e.g. /blog/,
url: "http://2015.hackference.co.uk" # the base hostname & protocol for your site
#baseurl: "" # Dev Path
#url: "http://127.0.0.1:4000/" #Dev Path
cfp: "http://cfp.hackference.co.uk"
twitter_username: jakelprice
github_username:  jakeprice86
collections:
  speakers:
    output: true


# Build settings
markdown: kramdown
