# Site settings
title: Hackference
email: mike@hackference.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Hackference, a conference and hackathon built to inspire.
  Crafted by developers for developers, giving you more things to play with.
twitter_username: hackferencebrum
github_username:  hackference

# Build settings
markdown: kramdown

# Exclude for deploy
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

sass:
  style: compressed
